### ISSUE TITLE
Staff section for mobile should flip over on click

### ISSUE THREAD

**Issue by msclal** [citrushack/citrushack2023#101]
<img width="392" alt="Screenshot 2023-03-29 at 6 53 21 PM" src="https://user-images.githubusercontent.com/60799725/228707752-cd67b78c-17fa-4333-a385-ad1d128fa1f6.png">

(MOBILE) when you click, card should flip over and show the back side info (name and position)

**Comment by minsooerickim** [comment]
@msclal does it tho, it takes me to their LinkedIn fo rme

edit: i read that wrong, my bad. immigrant issues sorry. but yes thanks for the clarification msclal

**Comment by minsooerickim** [comment]
@Alamode89 I think your going to love this issue
