### ISSUE TITLE
support cards should flip over on click (MOBILE)

### ISSUE THREAD

**Issue by minsooerickim** [citrushack/citrushack2023#106]
almost the same issue as #101 

so maybe whoever is doing #101 can also do this

![image](https://user-images.githubusercontent.com/62922309/228761397-d59e45e2-0f68-4a44-b8fb-6f6705697efd.png)

all the above cards should flip over when you click on them (mobile).

**Comment by NovaSagittarii** [comment]
click on the left, it flips
click on the right, it links you somewhere (and also flips when you get back)

🤔

**Comment by minsooerickim** [comment]
> click on the left, it flips click on the right, it links you somewhere (and also flips when you get back)
> 
> 🤔

honestly not a bad idea, but that does kinda come with the assumption that the user knows where to click for what effect.

marketing decided to jus display the backsides for mobile tho so i think we shud be guddd
