### ISSUE TITLE
make email templates with sendgrid

### ISSUE THREAD

**Issue by minsooerickim** [citrushack/citrushack2023#15]
https://sendgrid.com/solutions/email-api/dynamic-email-templates/

we need email templates for many things
- register
- acceptance
- reminders
- etc..

**Comment by paulian7** [comment]
**Updates**

- All email templates are finished and ready. I'll attach previews of them below.

<img width="571" alt="Screen Shot 2023-03-15 at 9 34 51 PM" src="https://user-images.githubusercontent.com/43308867/225515425-74786d8c-ddd6-43c9-b0f2-4e4778d471f7.png">

<img width="560" alt="Screen Shot 2023-03-15 at 9 35 20 PM" src="https://user-images.githubusercontent.com/43308867/225515481-1081d727-e29d-441d-8b66-17872e0d806d.png">

<img width="569" alt="Screen Shot 2023-03-15 at 9 35 34 PM" src="https://user-images.githubusercontent.com/43308867/225515501-3562a759-f798-47eb-90f0-9374dbb8c5dc.png">

<img width="555" alt="Screen Shot 2023-03-15 at 9 35 52 PM" src="https://user-images.githubusercontent.com/43308867/225515535-c88219e8-cbf2-4859-8e79-d2ec6d95c6eb.png">

<img width="570" alt="Screen Shot 2023-03-15 at 9 36 33 PM" src="https://user-images.githubusercontent.com/43308867/225515620-f9185fb5-0da9-4c13-a0dd-89e9c1124e34.png">

<img width="560" alt="Screen Shot 2023-03-15 at 9 36 48 PM" src="https://user-images.githubusercontent.com/43308867/225515645-b0aa9591-0450-4cb1-b75c-b5ddc2f1e86e.png">

<img width="562" alt="Screen Shot 2023-03-15 at 9 37 04 PM" src="https://user-images.githubusercontent.com/43308867/225515678-f7459bb1-caac-43f1-af14-95393226fcb3.png">

<img width="569" alt="Screen Shot 2023-03-15 at 9 37 22 PM" src="https://user-images.githubusercontent.com/43308867/225515712-2803d1f3-8457-47d8-bf4f-d411704ba019.png">

<img width="546" alt="Screen Shot 2023-03-15 at 9 37 38 PM" src="https://user-images.githubusercontent.com/43308867/225515754-493b295d-4874-49fb-8efb-8f2b984ae240.png">

<img width="558" alt="Screen Shot 2023-03-15 at 9 37 56 PM" src="https://user-images.githubusercontent.com/43308867/225515786-91b01cf5-917e-4fc7-b86f-5e1f0fdb3eda.png">
