### ISSUE TITLE
update schedule section with new design

### ISSUE THREAD

**Issue by minsooerickim** [citrushack/citrushack2023#22]

**Comment by paulian7** [comment]
- check the rough wireframe for an idea of what our schedule is supposed to look like: https://www.figma.com/file/SauEF2fzCcP75hj90BGDwt/UI-UX-Citrus-Hack-2023?node-id=0%3A1&t=YSjLfQ7sE17G703g-0

**Comment by msclal** [comment]
@minsooerickim @paulian7 

flag text needs to be flipped still (need to ask ui/ux team)
but how do we feel about this mobile version for schedule?
- retains schedule block structure of previous design
- preserves website theme + flag design

<img width="637" alt="image" src="https://user-images.githubusercontent.com/60799725/224580171-75b0d595-d25c-4029-8a0f-19d0ac1e21e5.png">

**Comment by minsooerickim** [comment]
@msclal looks gud to me. if possible though, i would make the texts a bit smaller and the space between the dots a bit tighter so we can fit all the events in a shorter 'flag pole', cuz we got a lotttt of events, and it seems like the pole is gon be like a million feet long.

i would aim to fit like 8 events per view like in cutiehack 
![image](https://user-images.githubusercontent.com/62922309/224582809-03110a23-4be2-4c18-901a-a4d8e698854a.png)

also add in the ending time? like (1-3pm instead of just 1pm)

**Comment by paulian7** [comment]
@msclal Amazing work! :) A few suggestions to add on is possibly centering each of the event's text with the dots. It feels like the text is a bit far too below each dot, so it might confuse some users.
