### ISSUE TITLE
fix firebase permissions

### ISSUE THREAD

**Issue by minsooerickim** [citrushack/citrushack2023#4]
currently, everybody can read/write which isn't ideal

i think you can define read/write rules in the firebase configurations

I think it would be good to only allow admins to read/write somehow

note: we use firebase to store resumes and mongo for everything else if anyone was wondering

**Comment by msclal** [comment]
<img width="1286" alt="Screenshot 2023-02-01 at 12 33 06 AM" src="https://user-images.githubusercontent.com/60799725/215991199-0ecf6c7c-cbe2-47ef-8d6f-7bc1f393c72c.png">

For now, I set up read/write authorization based on an example admin email
-any authenticated user can read
-any authorized user can read/write with the email "admin@gmail.com"

**Comment by minsooerickim** [comment]
better alternative, store pdfs in mongodb using gridFS

**Comment by minsooerickim** [comment]
i have done it 🚀
