### ISSUE TITLE
nav.cy.ts inconsistency between local and remote Github actions

### ISSUE THREAD

**Issue by minsooerickim** [citrushack/citrushack2023#76]
bro the nav.cy.ts is being so fkn wonky

it passes locally but not on github

locally, it doesn't add a trailing slash to URL but on github it does, like wtf.

please fix 🙏🏻 @NovaSagittarii

**Comment by NovaSagittarii** [comment]
oh dear

**Comment by NovaSagittarii** [comment]
https://github.com/citrushack/citrushack2023/compare/6fd3be22ea2ace16dfcb3ee99b0ff8a107c46fbc..aa6ea8ef1f405a2fd7ea7fe74ce4f72cfe1b863f

comparing between last working and first failed test

**Comment by NovaSagittarii** [comment]
https://github.com/citrushack/citrushack2023/commit/8d1e8cd20fab55a69fe2dc96094e233961c116fd

maybe relevant change
![image](https://user-images.githubusercontent.com/12877445/225365591-e0465225-01ff-4af3-8eee-8adf7f915e59.png)

maybe cypress related issues?
https://github.com/cypress-io/cypress/issues/2101
https://github.com/cypress-io/cypress/issues/3540
https://github.com/cypress-io/cypress/issues/9360

no idea whats up with the difference in behaviors tho, i guess next step is checking the environment it runs in

does weird things on my local machine with headless too :(
![image](https://user-images.githubusercontent.com/12877445/225374524-725f5d1f-82ad-41b0-8600-56544567e6e1.png)

**Comment by minsooerickim** [comment]
damn this is a high risk/thinking/headache low reward situation here. i think we shud just scrap this test and backlog it LOLL @NovaSagittarii

**Comment by NovaSagittarii** [comment]
https://github.com/citrushack/citrushack2023/commit/f264f1f45d567946d042499d430f55c8ded97b20#commitcomment-104593042 hey wait a minute

**Comment by NovaSagittarii** [comment]
okay so, 404 "go back" always redirects to a website with a trailing slash
however, in cypress config, github actions will trim the trailing slash while local doesn't do anything to it
