### ISSUE TITLE
reroute wrong paths

### ISSUE THREAD

**Issue by minsooerickim** [citrushack/citrushack2023#8]
if u go to `/admin` as a non-admin, you get an error 

redirect them back to the home page or something like that instead of erroring

**Comment by swooshoo** [comment]
hey minsoo I accessed localhost and /admin and the page seems to work normally

**Comment by swooshoo** [comment]
<img width="1354" alt="image" src="https://user-images.githubusercontent.com/102700240/216491094-3562da66-db74-4be4-a162-6c96b512ab43.png">

**Comment by swooshoo** [comment]
<img width="967" alt="image" src="https://user-images.githubusercontent.com/102700240/216492384-f2cee297-7271-4af1-9e91-4ef1d6333b9f.png">
router.push() seems to be redirecting the admin page correctly.

**Comment by minsooerickim** [comment]
> <img alt="image" width="1354" src="https://user-images.githubusercontent.com/102700240/216491094-3562da66-db74-4be4-a162-6c96b512ab43.png">

try removing the callback stuff in ur URL and go to `localhost:3000/admin`; it still bugs out for me
